/**
 * Mirrors `supabase gen types typescript --schema public` for the schema in
 * supabase/migrations/0001_init.sql.
 *
 * Regenerate against a live project with:
 *   npx supabase gen types typescript --project-id <id> --schema public > src/types/database.ts
 *
 * Keep the nullability here identical to the migration: almost every content
 * column is nullable on purpose (HARD CONSTRAINT 3 — the database must never
 * reject a report).
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          role: string;
          is_active: boolean;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id: string;
          username: string;
          full_name?: string | null;
          role?: string;
          is_active?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          username?: string;
          full_name?: string | null;
          role?: string;
          is_active?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      reports: {
        Row: {
          id: string;
          ticket: string;
          created_at: string;
          updated_at: string;
          status: string;
          priority: string;
          report_class: string | null;
          incident_at: string | null;
          incident_at_text: string | null;
          narrative: string | null;
          location_text: string | null;
          desa: string | null;
          kecamatan: string | null;
          kabupaten: string | null;
          provinsi: string | null;
          reported_party: string | null;
          reported_party_role: string | null;
          category: string | null;
          category_raw: string | null;
          item_given: string | null;
          item_value: number | null;
          item_value_text: string | null;
          recipients_estimate: number | null;
          witness_count: number | null;
          identity_disclosed: boolean;
          reporter_name: string | null;
          reporter_address: string | null;
          reporter_contact: string | null;
          has_evidence: boolean;
          evidence_note: string | null;
          extra: Json;
          source: string;
          source_meta: Json;
          payload: Json;
          raw_transcript: string | null;
          completeness: number;
          parse_warnings: string[];
          admin_notes: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          is_archived: boolean;
        };
        Insert: {
          id?: string;
          // generated by the reports_before_write trigger when omitted
          ticket?: string;
          created_at?: string;
          updated_at?: string;
          status?: string;
          priority?: string;
          report_class?: string | null;
          incident_at?: string | null;
          incident_at_text?: string | null;
          narrative?: string | null;
          location_text?: string | null;
          desa?: string | null;
          kecamatan?: string | null;
          kabupaten?: string | null;
          provinsi?: string | null;
          reported_party?: string | null;
          reported_party_role?: string | null;
          category?: string | null;
          category_raw?: string | null;
          item_given?: string | null;
          item_value?: number | null;
          item_value_text?: string | null;
          recipients_estimate?: number | null;
          witness_count?: number | null;
          identity_disclosed?: boolean;
          reporter_name?: string | null;
          reporter_address?: string | null;
          reporter_contact?: string | null;
          has_evidence?: boolean;
          evidence_note?: string | null;
          extra?: Json;
          source?: string;
          source_meta?: Json;
          payload?: Json;
          raw_transcript?: string | null;
          completeness?: number;
          parse_warnings?: string[];
          admin_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          is_archived?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["reports"]["Insert"]>;
        Relationships: [];
      };
      attachments: {
        Row: {
          id: string;
          report_id: string;
          storage_path: string;
          file_name: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          caption: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          storage_path: string;
          file_name?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          caption?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["attachments"]["Insert"]>;
        Relationships: [];
      };
      report_events: {
        Row: {
          id: string;
          report_id: string;
          actor_id: string | null;
          event_type: string;
          from_value: string | null;
          to_value: string | null;
          detail: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          actor_id?: string | null;
          event_type: string;
          from_value?: string | null;
          to_value?: string | null;
          detail?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["report_events"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: {
      generate_ticket: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};

export type ReportRow = Database["public"]["Tables"]["reports"]["Row"];
export type ReportInsert = Database["public"]["Tables"]["reports"]["Insert"];
export type ReportUpdate = Database["public"]["Tables"]["reports"]["Update"];
export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];
export type AttachmentRow = Database["public"]["Tables"]["attachments"]["Row"];
export type ReportEventRow = Database["public"]["Tables"]["report_events"]["Row"];
